default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: localhost
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: recipe_development

test:
  <<: *default
  database: recipe_test

production:
  <<: *default
  database: recipe_production
  username: recipe_app
  password: <%= ENV['RECIPE_DATABASE_PASSWORD'] %>
